### PR TITLE
1 add the capability to prescribe existing segmentations to individual findings

### PR DESCRIPTION
**Pull request by naucoin**
Added a label map volume selector and use that segmentation to initialise the finding segmenation.
I've tested it with a simple data set, let me know if there are use cases where it fails.

### CODE REVIEW

**Comment by fedorov** [comment]
Nicole, geometry consistency checks should take place at the time label is selected in the popup, and resampling should be done at the time label selection is accepted.

I've just tested this, and resampling was attempted only after I tried to open the Editor panel, and at that time mismatch of geometry was reported on the console, and Slicer crashed. This is not expected behavior, even if my inputs were bogus. Let's take a look at the project week together, or when back in Boston.

**Comment by fedorov** [comment]
mentioning #1 as the motivating issue

**Comment by naucoin** [comment]
Thanks for the feedback, I can definitely make it stop crashing, but I wasn't able to get the current workflow to give me the volume against which to compare when the prior segmentation drop down is being set. I'll see if the selection can be moved elsewhere in the workflow.

**Comment by naucoin** [comment]
Updated the Slicer Volumes logic to avoid the crash:
http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24352

**Comment by fedorov** [comment]
I just realized I cannot build Slicer for some reason, so cannot test this at the moment. Will try a fresh build.

**Pull request merged**
